Repository guibranco/dotnet-aicommitmessage, pull requests merged in 2024-10, with the labels that each got.

#59 Enhance environment variable management and refactor services
  Src/AiCommitMessage/Services/InstallHookService.cs
  Src/AiCommitMessage/Utility/Output.cs
Labels: enhancement, ☑️ auto-merge, size/XS, documentation

#62 Enhance commit message generation with issue extraction +semver: minor
  .config/dotnet-tools.json
  Src/AiCommitMessage/AiCommitMessage.csproj
  Src/AiCommitMessage/Services/GenerateCommitMessageService.cs
  Src/AiCommitMessage/Utility/BranchNameUtility.cs
  Src/AiCommitMessage/Utility/GitProvider.cs
  Tests/AiCommitMessage.Tests/Utility/BranchNameUtilityTests.cs
Labels: 📝 documentation, enhancement, help wanted, good first issue, ☑️ auto-merge, 🧪 tests, hacktoberfest, 🕓 medium effort, size/L, Review effort [1-5]: 4, gitauto, tests

#66 Update installation command in prepare-commit-msg script
  .githooks/prepare-commit-msg
Labels: enhancement, ☑️ auto-merge, size/XS, Review effort [1-5]: 2

#68 Enhance InstallHookService with Directory Existence Check
  Src/AiCommitMessage/Services/InstallHookService.cs
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 2

#75 Update InstallHookService.cs
  .github/workflows/infisical-secrets-check.yml
  Src/AiCommitMessage/Services/InstallHookService.cs
Labels: enhancement, size/XS, Review effort [1-5]: 2

#76 Create config.yml
  config.yml
Labels: enhancement, ☑️ auto-merge, size/XS, Review effort [1-5]: 1

#77 Rename config.yml to _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/XS, Review effort [1-5]: 1

#78 Update _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/XS, Review effort [1-5]: 1

#79 Update _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/XS, Review effort [1-5]: 1

#80 Update _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/XS, Review effort [1-5]: 2

#81 Update _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/XS, Review effort [1-5]: 2

#82 Update _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/L, Review effort [1-5]: 2

#83 Update _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/M, Review effort [1-5]: 2

#84 Update _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/XS, Review effort [1-5]: 2

#85 Update _config.yml
  _config.yml
Labels: enhancement, ☑️ auto-merge, size/S, Review effort [1-5]: 2

#88 Update prepare-commit-msg +semver: minor
  .githooks/prepare-commit-msg
Labels: ☑️ auto-merge, size/XS

#90 Update Output.cs +semver: minor
  Src/AiCommitMessage/Utility/Output.cs
Labels: 🐛 bug, enhancement, ☑️ auto-merge, 🕒 low effort, size/XS

#91 Update README.md +semver: minor
  README.md
Labels: ☑️ auto-merge, size/XS

#94 Update README.md +semver: minor
  README.md
Labels: ☑️ auto-merge, size/S

#96 Add changes to GenerateCommitMessageService
  Src/AiCommitMessage/Services/GenerateCommitMessageService.cs
  Src/AiCommitMessage/Services/GitHelper.cs
Labels: 📝 documentation, enhancement, 🧪 tests, 🚦 awaiting triage, hacktoberfest, 🕓 medium effort

#98 Update prepare-commit-msg +semver: minor
  .githooks/prepare-commit-msg
  Src/AiCommitMessage/Services/GenerateCommitMessageService.cs
Labels: ☑️ auto-merge, size/M

#101 Update README.md
  README.md
Labels: ☑️ auto-merge, size/XS
