Repository guibranco/dotnet-aicommitmessage, pull requests merged in 2024-12, with the labels that each got.

#142 Update README.md
  README.md
Labels: ☑️ auto-merge, size/XS

#143 Update _config.yml
  _config.yml
Labels: ☑️ auto-merge, size/XS

#148 Create CONTRIBUTING.MD
  CONTRIBUTING.MD
Labels: 📝 documentation, enhancement, ☑️ auto-merge, size/M

#150 Update ci.yml
  .github/workflows/ci.yml
Labels: ☑️ auto-merge, size/XS

#155 Feat/issue 154 llama support
  README.md
  Src/AiCommitMessage/AiCommitMessage.csproj
  Src/AiCommitMessage/Options/SetSettingsOptions.cs
  Src/AiCommitMessage/Services/GenerateCommitMessageService.cs
  Src/AiCommitMessage/Services/SettingsService.cs
  Src/AiCommitMessage/Utility/EnvironmentLoader.cs
  Tests/AiCommitMessage.Tests/Services/GenerateCommitMessageServiceTests.cs
Labels: 📝 documentation, enhancement, 🧪 tests, hacktoberfest, 🕔 high effort, LLM, Azure AI

#156 Create contributors readme update workflow
  .github/workflows/contributors-readme.yml
  README.md
  Src/AiCommitMessage/Options/SetSettingsOptions.cs
  Src/AiCommitMessage/Services/GenerateCommitMessageService.cs
  Src/AiCommitMessage/Utility/EnvironmentLoader.cs
  Tests/AiCommitMessage.Tests/Services/GenerateCommitMessageServiceTests.cs
Labels: ☑️ auto-merge, size/L

#159 Update contributors-readme.yml
  .github/workflows/contributors-readme.yml
Labels: ☑️ auto-merge, size/XS

#161 Update README.md
  README.md
Labels: ☑️ auto-merge, size/XS
